services:

  nginx:
    image: nginx:stable
    container_name: imgstream-nginx
    ports:
      - "443:443"
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      - ${SSL_CERT_PATH}:/etc/nginx/certs/fullchain.pem:ro
      - ${SSL_KEY_PATH}:/etc/nginx/certs/key.pem:ro
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
    depends_on:
      - varnish1
    networks:
      - imgstream-network
    restart: unless-stopped

  varnish1:
    image: varnish:latest
    container_name: imgstream-varnish1
    ports:
      - "6081:6081"
      - "6082:6082"
    volumes:
      - ${VARNISH_VCL}:/etc/varnish/default.vcl:ro
    command: [ "varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,256m", "-a", ":6081" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - elysia1
    networks:
      - imgstream-network
    restart: unless-stopped

  elysia1:
    build: ./server
    container_name: imgstream-elysia1
    env_file:
      - .env
    networks:
      - imgstream-network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: imgstream-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - imgstream-network
    restart: unless-stopped

networks:
  imgstream-network:
    driver: bridge

volumes:
  redis-data:
