services:

  nginx:
    image: nginx:stable
    container_name: imgstream-nginx
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - varnish1
    networks:
      - imgstream-network
    restart: unless-stopped

  varnish1:
    image: varnish:latest
    container_name: imgstream-varnish1

    ports:
      - "6081:6081" # my port : port inside container (Varnish default port)
      - "6082:6082" # Varnish admin port
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    command: [ "varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,256m", "-a", ":6081" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - elysia1
    networks:
      - imgstream-network
    restart: unless-stopped

  elysia1:
    build: ./elysia1
    container_name: imgstream-elysia1

    environment:
      - NODE_ENV=production
      - PORT=3001
      - YC_ACCESS_KEY_ID=${YC_ACCESS_KEY_ID}
      - YC_SECRET_ACCESS_KEY=${YC_SECRET_ACCESS_KEY}
    # connect to container to a shared Docker network
    networks:
      - imgstream-network
    restart: unless-stopped

networks:
  imgstream-network:
    driver: bridge
